name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  # ---------------------------------------------------------------------------
  # Create GitHub Release
  # ---------------------------------------------------------------------------
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            See [CHANGELOG](https://github.com/rpaweb/owlook/blob/master/CHANGELOG.md) for details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
